<?php


namespace backend\controllers;


use yii\helpers\Url;
use yii\rest\ActiveController;
use yii\web\Controller;

class BaseController extends ActiveController
{


    public function beforeAction($action)
    {
        if (\Yii::$app->user->identity->banned) {
            return  $this->asJson(["error"=>"You have been banned!"])->send();
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }


}