version: '3.2'

services:

  nginx:
    image: nginx
    ports:
      - "80:80"
    links:
      - app

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/app
      - ./logs/nginx-access.log:/var/log/nginx/access.log
      - ./logs/nginx-error.log:/var/log/nginx/error.log

  rbmq:
    image: 'bitnami/rabbitmq:latest'
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_PASSWORD=my_password
      - RABBITMQ_DISK_FREE_LIMIT=1024
    depends_on:
      - app
      - consoleapp

  app:
    build: DockerImages/App
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
    depends_on:
      - mysql

  consoleapp:
    build: DockerImages/Console
    volumes:
      - ./:/app
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_DATABASE=yii2advanced
      - MYSQL_USER=yii2advanced
      - MYSQL_PASSWORD=secret


  pphpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8000:8000'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: verysecret




  #  php-fpm:
  #    image: php:fpm
  #    volumes:
  #      - ./:/app
  #    ports:
  #      - "9000:9000"

  #pgsql:
  #  image: postgres:9.5
  #  environment:
  #    - POSTGRES_DB=yii2advanced
  #    - POSTGRES_USER=yii2advanced
  #    - POSTGRES_PASSWORD=secret