<?php


namespace frontend\controllers;


use yii\helpers\Url;
use yii\web\Controller;

class BaseController extends Controller
{


    public function beforeAction($action)
    {
        if (\Yii::$app->user->identity->banned and \Yii::$app->request->url != Url::to(["admin/ban-page"])) {
            return  $this->redirect("/admin/ban-page")->send();
        }
        if(!\Yii::$app->user->identity->banned and \Yii::$app->request->url == Url::to(["admin/ban-page"])) {
            return  $this->goHome()->send();
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionBanPage()
    {
        return $this->render("ban_page");
    }

}