<?php


namespace frontend\controllers;


use yii\helpers\Url;
use yii\web\Controller;

class BaseController extends Controller
{


    /**
     * Redirecting for banned users
     * @param $action
     * @return bool|void
     * @throws \yii\web\BadRequestHttpException
     */
    public function beforeAction($action)
    {
        if (\Yii::$app->user->identity->banned
            and \Yii::$app->request->url != Url::to(["admin/ban-page"])
            and \Yii::$app->request->url != Url::to(["site/logout"]) ) {
            return $this->redirect("/admin/ban-page")->send();
        }
        if (!\Yii::$app->user->identity->banned and \Yii::$app->request->url == Url::to(["admin/ban-page"])) {
            return $this->goHome()->send();
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionBanPage()
    {
        return $this->render("ban_page");
    }

}